---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: acm.managedserviceaccount
  namespace: openshift-gitops
spec:
  generators:
  - matrix:
      generators:
        - list:
            elements:
              - policy: acm_managedserviceaccount
                revision: main
        - list:
            elements:
            - cluster: ocphbprd
