---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: acm.feature-flags-placement
  namespace: openshift-gitops
spec:
  generators:
  - matrix:
      generators:
        - list:
            elements:
              - policy: acm_feature-flags-placement
                revision: main
        - list:
            elements:
            - cluster: ocphbprd
