---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: ingress-gen
policyDefaults:
  namespace: bry-tam-policies
  remediationAction: enforce
  consolidateManifests: false
  ## turn off the default compliance annotations
  categories: []
  controls: []
  standards: []
  policySets:
    - cluster-configs-ingress

placementBindingDefaults:
  name: "cluster-config-binding"

policies:
  - name: ingress-certificate
    dependencies:
      - name: cert-manager-clusterissuer
        compliance: "Compliant"
    manifests:
      - path: certificate.yml
        name: ingress-certificate
      - path: cert-ready.yml
        name: ingress-cert-ready
        remediationAction: InformOnly
      - path: ingress-cert.yml
        name: ingress-default-certs
        extraDependencies:
          - name: ingress-cert-ready
            kind: ConfigurationPolicy
            compliance: "Compliant"



policySets:
  - name: cluster-configs-ingress
    placement:
      placementName: per-cluster-placement
