---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ocp.operator.acm
  namespace: openshift-gitops
spec:
  generators:
  - matrix:
      generators:
        - list:
            elements:
              - policy: ocp_operator_acm
                revision: main
        - list:
            elements:
            - cluster: ocphbprd
