---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ocp.operator.talm
  namespace: openshift-gitops
spec:
  generators:
  - matrix:
      generators:
        - list:
            elements:
              - policy: ocp_operator_talm
                revision: main
        - list:
            elements:
            - cluster: ocphbprd
