---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: monitoring-gen
policyDefaults:
  namespace: bry-tam-policies
  remediationAction: enforce
  consolidateManifests: false
  ## turn off the default compliance annotations
  categories: []
  controls: []
  standards: []
  policySets:
    - cluster-configs-monitoring
placementBindingDefaults:
  name: "cluster-config-monitoring-binding"

policies:
  - name: ocp-monitoring
    manifests:
      - path: ./cluster-monitoring-config.yml
        name: cluster-monitoring-config

      - path: ./user-workload-monitoring-config.yml
        name: user-workload-monitoring-config

policySets:
  - name: cluster-configs-monitoring
    placement:
      per-cluster-placement
